name: Publish Release
on:
    release:
        types: [published]
    workflow_dispatch:

permissions:
    contents: read
    pages: write
    id-token: write

jobs:
  # Announce on Discord
  announce:
    name: Announce on Discord
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Rokit
      uses: CompeyDev/setup-rokit@v0.1.0

    - name: Send webhook
      env:
        WEBHOOK_URL: ${{ secrets.UPDATE_WEBHOOK_URL }}
      run: |
        VERSION="${{ github.ref_name }}"
        lune run .lune/discord.luau "$WEBHOOK_URL" "announcement" "$PROJECT" "$VERSION"

  # Publish to wally
  publish-wally:
    name: Publish package to Wally
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Rokit
      uses: CompeyDev/setup-rokit@v0.1.0

    - name: Log In
      env:
        WALLY_AUTH: ${{ secrets.WALLY_AUTH_TOKEN }}
      run: |
        mkdir ~/.wally
        printenv WALLY_AUTH > ~/.wally/auth.toml

    - name: Publish
      run: |
        wally publish